name: frappe
description: A starting point for Dart libraries or applications.
version: 0.3.0
homepage: https://github.com/fromlabs/frappe
author: Roberto Tassi <roberto.tassi@fromlabs.org>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.8.0+1
  optional: ^4.1.0
  tuple: ^1.0.3

dev_dependencies:
  test: ^1.12.0