name: _frappe_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/frappe
  - packages/brew
  - packages/flutter_frappe
  - packages/flutter_brew
  - packages/flutter_frappe/example/petrol_pump
  - packages/flutter_frappe/example/flutter_petrol_pump
  - packages/flutter_brew/example/petrol_pump
  - packages/flutter_brew/example/flutter_petrol_pump
