name: frappe
description: A starting point for Dart libraries or applications.
version: 0.2.0
homepage: https://github.com/fromlabs/frappe
author: Roberto Tassi <roberto.tassi@fromlabs.org>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:
  pedantic: ^1.0.0  
  optional: ^3.1.0
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.0.0