name: frappe
description: A starting point for Dart libraries or applications.
version: 0.3.0
homepage: https://github.com/fromlabs/frappe
author: Roberto Tassi <roberto.tassi@fromlabs.org>

environment:
  sdk: '>=2.11.0-218.0.dev <3.0.0'

dependencies:
  #pedantic: ^1.10.0-nullsafety.1
  #optional: ^5.0.0
  #tuple: ^1.0.3

dev_dependencies:
  # test: any