name: petrol_pump
description: A starting point for Dart libraries or applications.
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.11.0-218.0.dev <3.0.0'

dependencies:
  pedantic: ^1.10.0-nullsafety.1
  built_collection: ^4.3.2

  frappe:
    path: ../..

dev_dependencies:
  test: ^1.16.0-nullsafety.6
