name: petrol_pump
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Roberto Tassi <roberto.tassi@fromlabs.org>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:
  pedantic: ^1.0.0
  built_collection: ^4.2.0
  built_value: ^7.0.0

  frappe:
    path: ../../..

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.4.0
  built_value_generator: ^7.0.0
