name: petrol_pump
description: A starting point for Dart libraries or applications.
version: 0.3.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.8.0+1
  built_collection: ^4.3.2
  built_value: ^7.0.9

  frappe:
    path: ../../..

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
