name: flutter_petrol_pump
description: A new Flutter project.
version: 0.3.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  pedantic: ^1.8.0+1
  quiver: ^2.0.5
  provider: ^4.0.4
  audioplayers: ^0.14.0

  petrol_pump:
    path: ../petrol_pump

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/nozzle1.png
    - assets/nozzle2.png
    - assets/nozzle3.png
    - assets/beep.wav
    - assets/fast.wav
    - assets/slow.wav
